# Walmart Analysis part 1

In [1]:
import pandas as pd
df = pd.read_csv("Walmart sales data.csv")

In [2]:
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

In [3]:
df['promotion_type'] = df['promotion_type'].fillna('No Promotion')

In [4]:
df['revenue'] = df['quantity_sold'] * df['unit_price']

In [5]:
df['forecast_error'] = abs(df['forecasted_demand'] - df['actual_demand'])

In [6]:
print(df.head())
print(df.info())

   transaction_id  customer_id  product_id product_name     category  \
0               1         2824         843       Fridge  Electronics
1               2         1409         135           TV  Electronics
2               3         5506         391       Fridge  Electronics
3               4         5012         710   Smartphone  Electronics
4               5         4657         116       Laptop  Electronics

   quantity_sold  unit_price    transaction_date  store_id   store_location  \
0              3      188.46 2024-03-31 21:46:00         3        Miami, FL
1              4     1912.04 2024-07-28 12:45:00         5       Dallas, TX
2              4     1377.75 2024-06-10 04:55:00         1  Los Angeles, CA
3              5      182.31 2024-08-15 01:03:00         5        Miami, FL
4              3      499.28 2024-09-13 00:45:00         6      Chicago, IL

   ...  promotion_applied       promotion_type  weather_conditions  \
0  ...               True         No Promotion              Stormy
1  ...               True  Percentage Discount               Rainy
2  ...              False         No Promotion               Sunny
3  ...               True  Percentage Discount               Sunny
4  ...              False                                    Sunny

   holiday_indicator   weekday  stockout_indicator forecasted_demand  \
0              False    Friday                True               172
1              False    Monday                True               109
2              False   Tuesday                True               289
3               True    Sunday               False               174
4              False  Thursday                True               287

   actual_demand  revenue forecast_error
0            179   565.38              7
1            484  7648.16            375
2            416  5511.00            127
3            446   911.55            272
4            469  1497.84            182

[5 rows x 30 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   transaction_id          5000 non-null   int64
 1   customer_id             5000 non-null   int64
 2   product_id              5000 non-null   int64
 3   product_name            5000 non-null   object
 4   category                5000 non-null   object
 5   quantity_sold           5000 non-null   int64
 6   unit_price              5000 non-null   float64
 7   transaction_date        5000 non-null   datetime64[ns]
 8   store_id                5000 non-null   int64
 9   store_location          5000 non-null   object
 10  inventory_level         5000 non-null   int64
 11  reorder_point           5000 non-null   int64
 12  reorder_quantity        5000 non-null   int64
 13  supplier_id             5000 non-null   int64
 14  supplier_lead_time      5000 non-null   int64
 15  customer_age            5000 non-null   int64
 16  customer_gender         5000 non-null   object
 17  customer_income         5000 non-null   float64
 18  customer_loyalty_level  5000 non-null   object
 19  payment_method          5000 non-null   object
 20  promotion_applied       5000 non-null   bool
 21  promotion_type          5000 non-null   object
 22  weather_conditions      5000 non-null   object
 23  holiday_indicator       5000 non-null   bool
 24  weekday                 5000 non-null   object
 25  stockout_indicator      5000 non-null   bool
 26  forecasted_demand       5000 non-null   int64
 27  actual_demand           5000 non-null   int64
 28  revenue                 5000 non-null   float64
 29  forecast_error          5000 non-null   int64
dtypes: bool(3), datetime64[ns](1), float64(3), int64(14), object(9)
memory usage: 1.0+ MB
None

In [7]:
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus
from getpass import getpass

In [8]:
user = "root"
password = getpass("enter mysql password: ")
host = "localhost"
port = 3306
database_name = "walmart_db"

engine = create_engine(
    f"mysql+pymysql://{user}:{quote_plus(password)}@{host}:{port}/"
)

with engine.connect() as conn:
    conn.execute(text(f"create database if not exists {database_name}"))
    conn.commit()

print(f"{database_name} database created successfully.")

enter mysql password:  ········

walmart_db database created successfully.

In [9]:
engine = create_engine(
    f"mysql+pymysql://root:{quote_plus(password)}@localhost:3306/walmart_db"
)

print("Connected to walmart_db successfully.")

Connected to walmart_db successfully.

In [10]:
df.to_sql(
    name="walmart_sales",
    con=engine,
    if_exists='replace',
    index=False
)

print("Data Stored in mysql successfully.")

Data Stored in mysql successfully.

In [11]:
query = """
SELECT *
FROM walmart_sales;
"""

In [12]:
result = pd.read_sql(query,engine)
result

,transaction_id,customer_id,product_id,product_name,category,quantity_sold,unit_price,transaction_date,store_id,store_location,...,promotion_applied,promotion_type,weather_conditions,holiday_indicator,weekday,stockout_indicator,forecasted_demand,actual_demand,revenue,forecast_error
0,1,2824,843,Fridge,Electronics,3,188.46,2024-03-31 21:46:00,3,"Miami, FL",...,1,No Promotion,Stormy,0,Friday,1,172,179,565.38,7
1,2,1409,135,TV,Electronics,4,1912.04,2024-07-28 12:45:00,5,"Dallas, TX",...,1,Percentage Discount,Rainy,0,Monday,1,109,484,7648.16,375
2,3,5506,391,Fridge,Electronics,4,1377.75,2024-06-10 04:55:00,1,"Los Angeles, CA",...,0,No Promotion,Sunny,0,Tuesday,1,289,416,5511.00,127
3,4,5012,710,Smartphone,Electronics,5,182.31,2024-08-15 01:03:00,5,"Miami, FL",...,1,Percentage Discount,Sunny,1,Sunday,0,174,446,911.55,272
4,5,4657,116,Laptop,Electronics,3,499.28,2024-09-13 00:45:00,6,"Chicago, IL",...,0,,Sunny,0,Thursday,1,287,469,1497.84,182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,6898,852,Headphones,Appliances,1,682.15,2024-07-08 06:13:00,17,"New York, NY",...,0,No Promotion,Sunny,0,Wednesday,1,257,294,682.15,37
4996,4997,8412,886,Laptop,Appliances,3,1418.09,2024-02-07 11:30:00,16,"Los Angeles, CA",...,1,No Promotion,Sunny,1,Sunday,1,388,397,4254.27,9
4997,4998,8331,934,Fridge,Electronics,5,398.66,2024-08-20 00:38:00,16,"New York, NY",...,1,No Promotion,Cloudy,0,Thursday,1,314,204,1993.30,110
4998,4999,7505,439,Laptop,Appliances,3,1000.95,2024-08-26 11:05:00,16,"Miami, FL",...,1,No Promotion,Stormy,0,Tuesday,0,488,144,3002.85,344
4999,5000,1003,926,Washing Machine,Appliances,1,710.03,2024-02-09 01:27:00,12,"New York, NY",...,1,BOGO,Stormy,1,Wednesday,0,142,148,710.03,6

## Data Understanding And Cleaning

In [13]:
# 1.How many transactions are available in the dataset?  
query = """
select count(transaction_id) as Total_transactions 
from walmart_sales;
"""

In [14]:
result = pd.read_sql(query,engine)
result

   Total_transactions
0                5000

In [15]:
#2.what is the date range of sales data?
query = """ 
select
    min(transaction_date) as start_date,
    max(transaction_date) as end_date
from walmart_sales;
"""

In [16]:
result = pd.read_sql(query,engine)
result

           start_date            end_date
0 2024-01-01 00:31:00 2024-09-16 20:22:00

In [17]:
# 3.How many unique products, customers, stores, and suppliers are present?
query = """
select
count(distinct product_id) as unique_products,
count(distinct customer_id) as unique_stores,
count(distinct store_id ) as unique_stores,
count(distinct supplier_id)as unique_suppliers
from walmart_sales;"""

result = pd.read_sql(query,engine)
result

   unique_products  unique_stores  unique_stores  unique_suppliers
0              898           3848             20               401

In [18]:
# 4.Which columns have missing values? 
query = """
select
    sum(case when transaction_id is null then 1 else 0 end) as missing_transaction_id,
    sum(case when customer_id is null then 1 else 0 end) as missing_customer_id,
    sum(case when product_id is null then 1 else 0 end) as missing_product_id,
    sum(case when product_name is null then 1 else 0 end) as missing_product_name,
    sum(case when category is null then 1 else 0 end) as missing_category,
    sum(case when quantity_sold is null then 1 else 0 end) as missing_quantity_sold,
    sum(case when unit_price is null then 1 else 0 end) as missing_unit_price,
    sum(case when transaction_date is null then 1 else 0 end) as missing_transaction_date,
    sum(case when store_id is null then 1 else 0 end) as missing_store_id,
    sum(case when store_location is null then 1 else 0 end) as missing_store_location,
    sum(case when inventory_level is null then 1 else 0 end) as missing_inventory_level,
    sum(case when reorder_point is null then 1 else 0 end) as missing_reorder_point,
    sum(case when reorder_quantity is null then 1 else 0 end) as missing_reorder_quantity,
    sum(case when supplier_id is null then 1 else 0 end) as missing_supplier_id,
    sum(case when supplier_lead_time is null then 1 else 0 end) as missing_supplier_lead_time,
    sum(case when customer_age is null then 1 else 0 end) as missing_customer_age
from walmart_sales;"""

result = pd.read_sql(query, engine)
result

,missing_transaction_id,missing_customer_id,missing_product_id,missing_product_name,missing_category,missing_quantity_sold,missing_unit_price,missing_transaction_date,missing_store_id,missing_store_location,missing_inventory_level,missing_reorder_point,missing_reorder_quantity,missing_supplier_id,missing_supplier_lead_time,missing_customer_age
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
#5.Are there duplicate transactions?  
query = """
with cte as (
select *,
row_number() over (
partition by transaction_id 
order by transaction_id
) AS rn
from walmart_sales
)
SELECT *
FROM cte
WHERE rn > 1;
"""

result = pd.read_sql(query, engine)
result

Empty DataFrame
Columns: [transaction_id, customer_id, product_id, product_name, category, quantity_sold, unit_price, transaction_date, store_id, store_location, inventory_level, reorder_point, reorder_quantity, supplier_id, supplier_lead_time, customer_age, customer_gender, customer_income, customer_loyalty_level, payment_method, promotion_applied, promotion_type, weather_conditions, holiday_indicator, weekday, stockout_indicator, forecasted_demand, actual_demand, revenue, forecast_error, rn]
Index: []

[0 rows x 31 columns]

In [20]:
# 6.are data types correct?
query = """
select
    column_name,
    data_type,
    is_nullable,
    column_type
from information_schema.columns
where table_schema = database()
  and table_name = 'walmart_sales'
order by ordinal_position;
"""

result = pd.read_sql(query, engine)
result

               COLUMN_NAME DATA_TYPE IS_NULLABLE COLUMN_TYPE
0           transaction_id    bigint         YES      bigint
1              customer_id    bigint         YES      bigint
2               product_id    bigint         YES      bigint
3             product_name      text         YES        text
4                 category      text         YES        text
5            quantity_sold    bigint         YES      bigint
6               unit_price    double         YES      double
7         transaction_date  datetime         YES    datetime
8                 store_id    bigint         YES      bigint
9           store_location      text         YES        text
10         inventory_level    bigint         YES      bigint
11           reorder_point    bigint         YES      bigint
12        reorder_quantity    bigint         YES      bigint
13             supplier_id    bigint         YES      bigint
14      supplier_lead_time    bigint         YES      bigint
15            customer_age    bigint         YES      bigint
16         customer_gender      text         YES        text
17         customer_income    double         YES      double
18  customer_loyalty_level      text         YES        text
19          payment_method      text         YES        text
20       promotion_applied   tinyint         YES  tinyint(1)
21          promotion_type      text         YES        text
22      weather_conditions      text         YES        text
23       holiday_indicator   tinyint         YES  tinyint(1)
24                 weekday      text         YES        text
25      stockout_indicator   tinyint         YES  tinyint(1)
26       forecasted_demand    bigint         YES      bigint
27           actual_demand    bigint         YES      bigint
28                 revenue    double         YES      double
29          forecast_error    bigint         YES      bigint

In [21]:
# 7.Is transaction_date stored as a proper date?
query = """
select
     column_name,
     data_type,
     column_type
from information_schema.columns
where table_schema = database()
and table_name = 'walmart_sales'
and column_name = 'transaction_date';
"""

result = pd.read_sql(query,engine)
result

        COLUMN_NAME DATA_TYPE COLUMN_TYPE
0  transaction_date  datetime    datetime

In [22]:
#8.Are there abnormal values in quantity, price, inventory, demand, or income?  
query = """
select
    sum(case when quantity_sold < 0 then 1 else 0 end) as negative_quantity,
    sum(case when quantity_sold = 0 then 1 else 0 end) as zero_quantity,

    sum(case when unit_price < 0 then 1 else 0 end) as negative_price,
    sum(case when unit_price = 0 then 1 else 0 end) as zero_price,

    sum(case when inventory_level < 0 then 1 else 0 end) as negative_inventory,

    sum(case when forecasted_demand < 0 then 1 else 0 end) as negative_forecasted_demand,
    sum(case when actual_demand < 0 then 1 else 0 end) as negative_actual_demand,

    sum(case when customer_income < 0 then 1 else 0 end) as negative_income
from walmart_sales;
"""

result = pd.read_sql(query, engine)
result

,negative_quantity,zero_quantity,negative_price,zero_price,negative_inventory,negative_forecasted_demand,negative_actual_demand,negative_income
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
query = """
select
    min(quantity_sold) as min_quantity_sold,
    max(quantity_sold) as max_quantity_sold,

    min(unit_price) as min_unit_price,
    max(unit_price) as max_unit_price,

    min(inventory_level) as min_inventory_level,
    max(inventory_level) as max_inventory_level,

    min(forecasted_demand) as min_forecasted_demand,
    max(forecasted_demand) as max_forecasted_demand,

    min(actual_demand) as min_actual_demand,
    max(actual_demand) as max_actual_demand,

    min(customer_income) as min_customer_income,
    max(customer_income) as max_customer_income
from walmart_sales;
"""

result = pd.read_sql(query, engine)
result

,min_quantity_sold,max_quantity_sold,min_unit_price,max_unit_price,min_inventory_level,max_inventory_level,min_forecasted_demand,max_forecasted_demand,min_actual_demand,max_actual_demand,min_customer_income,max_customer_income
0,1,5,50.1,1999.85,0,500,100,500,90,510,20005.34,119999.78

In [24]:
query = """
select *
from walmart_sales
where quantity_sold <= 0
   or unit_price <= 0
   or inventory_level < 0
   or forecasted_demand < 0
   or actual_demand < 0
   or customer_income < 0;
"""

result = pd.read_sql(query, engine)
result

Empty DataFrame
Columns: [transaction_id, customer_id, product_id, product_name, category, quantity_sold, unit_price, transaction_date, store_id, store_location, inventory_level, reorder_point, reorder_quantity, supplier_id, supplier_lead_time, customer_age, customer_gender, customer_income, customer_loyalty_level, payment_method, promotion_applied, promotion_type, weather_conditions, holiday_indicator, weekday, stockout_indicator, forecasted_demand, actual_demand, revenue, forecast_error]
Index: []

[0 rows x 30 columns]

In [25]:
query = """
select *
from walmart_sales
where quantity_sold > (
        select avg(quantity_sold) + 3 * stddev(quantity_sold)
        from walmart_sales
    )
   or unit_price > (
        select avg(unit_price) + 3 * stddev(unit_price)
        from walmart_sales
    )
   or inventory_level > (
        select avg(inventory_level) + 3 * stddev(inventory_level)
        from walmart_sales
    )
   or forecasted_demand > (
        select avg(forecasted_demand) + 3 * stddev(forecasted_demand)
        from walmart_sales
    )
   or actual_demand > (
        select avg(actual_demand) + 3 * stddev(actual_demand)
        from walmart_sales
    )
   or customer_income > (
        select avg(customer_income) + 3 * stddev(customer_income)
        from walmart_sales
    );
"""

result = pd.read_sql(query, engine)
result

Empty DataFrame
Columns: [transaction_id, customer_id, product_id, product_name, category, quantity_sold, unit_price, transaction_date, store_id, store_location, inventory_level, reorder_point, reorder_quantity, supplier_id, supplier_lead_time, customer_age, customer_gender, customer_income, customer_loyalty_level, payment_method, promotion_applied, promotion_type, weather_conditions, holiday_indicator, weekday, stockout_indicator, forecasted_demand, actual_demand, revenue, forecast_error]
Index: []

[0 rows x 30 columns]

In [26]:
# 9.Which columns are categorical and numerical?  
query = """
select
    column_name,
    data_type,
    case
        when data_type in ('int', 'bigint', 'decimal', 'float', 'double') then 'numerical'
        when data_type in ('varchar', 'char', 'text') then 'categorical'
        when data_type in ('date', 'datetime', 'timestamp') then 'date/time'
        else 'other'
    end as column_category
from information_schema.columns
where table_schema = database()
  and table_name = 'walmart_sales'
order by ordinal_position;
"""

result = pd.read_sql(query, engine)
result

               COLUMN_NAME DATA_TYPE column_category
0           transaction_id    bigint       numerical
1              customer_id    bigint       numerical
2               product_id    bigint       numerical
3             product_name      text     categorical
4                 category      text     categorical
5            quantity_sold    bigint       numerical
6               unit_price    double       numerical
7         transaction_date  datetime       date/time
8                 store_id    bigint       numerical
9           store_location      text     categorical
10         inventory_level    bigint       numerical
11           reorder_point    bigint       numerical
12        reorder_quantity    bigint       numerical
13             supplier_id    bigint       numerical
14      supplier_lead_time    bigint       numerical
15            customer_age    bigint       numerical
16         customer_gender      text     categorical
17         customer_income    double       numerical
18  customer_loyalty_level      text     categorical
19          payment_method      text     categorical
20       promotion_applied   tinyint           other
21          promotion_type      text     categorical
22      weather_conditions      text     categorical
23       holiday_indicator   tinyint           other
24                 weekday      text     categorical
25      stockout_indicator   tinyint           other
26       forecasted_demand    bigint       numerical
27           actual_demand    bigint       numerical
28                 revenue    double       numerical
29          forecast_error    bigint       numerical

In [27]:
# Which columns can be used to create business KPIs? 
query = """
select
    count(*) as total_transactions,
    count(distinct customer_id) as total_customers,
    count(distinct product_id) as total_products,
    count(distinct store_id) as total_stores,
    count(distinct supplier_id) as total_suppliers,
    sum(quantity_sold) as total_units_sold,
    round(sum(quantity_sold * unit_price), 2) as total_revenue,
    round(avg(quantity_sold * unit_price), 2) as average_order_value
from walmart_sales;
"""

result = pd.read_sql(query, engine)
result

,total_transactions,total_customers,total_products,total_stores,total_suppliers,total_units_sold,total_revenue,average_order_value
0,5000,3848,898,20,401,14914.0,15263601.45,3052.72

In [28]:
# Which columns can be used to create business KPIs?  
query = """
select
    store_id,
    store_location,
    count(*) as total_transactions,
    sum(quantity_sold) as total_units_sold,
    round(sum(quantity_sold * unit_price), 2) as total_revenue
from walmart_sales
group by store_id, store_location
order by total_revenue desc;
"""

result = pd.read_sql(query, engine)
result

,store_id,store_location,total_transactions,total_units_sold,total_revenue
0,17,"Dallas, TX",61,190.0,213954.02
1,17,"Chicago, IL",58,185.0,211660.03
2,1,"Los Angeles, CA",65,196.0,210976.79
3,11,"Chicago, IL",51,171.0,205997.80
4,5,"Chicago, IL",59,175.0,205576.05
...,...,...,...,...,...
95,14,"Miami, FL",44,105.0,107133.24
96,4,"Dallas, TX",39,113.0,107053.65
97,4,"Miami, FL",40,108.0,105486.08
98,17,"New York, NY",32,90.0,91760.41
99,6,"New York, NY",32,94.0,80279.62

In [29]:
query = """
select
    product_id,
    product_name,
    category,
    inventory_level,
    reorder_point,
    reorder_quantity,
    case
        when inventory_level <= reorder_point then 'reorder needed'
        else 'stock available'
    end as stock_status
from walmart_sales
order by inventory_level asc;
"""

result = pd.read_sql(query, engine)
result

,product_id,product_name,category,inventory_level,reorder_point,reorder_quantity,stock_status
0,407,Smartphone,Appliances,0,130,151,reorder needed
1,568,Smartphone,Electronics,0,84,142,reorder needed
2,137,Washing Machine,Electronics,0,122,278,reorder needed
3,356,Smartphone,Electronics,0,148,276,reorder needed
4,179,Laptop,Appliances,0,84,200,reorder needed
...,...,...,...,...,...,...,...
4995,946,Fridge,Electronics,500,89,167,stock available
4996,855,Headphones,Electronics,500,58,160,stock available
4997,511,Fridge,Electronics,500,112,218,stock available
4998,374,TV,Appliances,500,128,273,stock available
4999,298,Camera,Appliances,500,144,253,stock available

In [30]:
query = """
select
    date_format(transaction_date, '%%Y-%%m') as sales_month,
    round(sum(quantity_sold * unit_price), 2) as monthly_revenue,
    sum(quantity_sold) as monthly_units_sold,
    count(*) as total_transactions
from walmart_sales
group by date_format(transaction_date, '%%Y-%%m')
order by sales_month;
"""

result = pd.read_sql(query, engine)
result

  sales_month  monthly_revenue  monthly_units_sold  total_transactions
0     2024-01       1731651.65              1672.0                 563
1     2024-02       1767062.38              1674.0                 560
2     2024-03       1833450.84              1809.0                 620
3     2024-04       1739800.75              1668.0                 561
4     2024-05       1786559.47              1768.0                 596
5     2024-06       1600978.97              1613.0                 542
6     2024-07       1878513.51              1833.0                 606
7     2024-08       2018315.81              1968.0                 656
8     2024-09        907268.07               909.0                 296

In [31]:
# Are negative or zero prices present?  
# Are negative quantities present?  
# Are demand values valid?  
query = """ select * from walmart_sales
where unit_price <= 0 or forecasted_demand < 0 
or actual_demand < 0;
"""

result = pd.read_sql(query ,engine)
result

Empty DataFrame
Columns: [transaction_id, customer_id, product_id, product_name, category, quantity_sold, unit_price, transaction_date, store_id, store_location, inventory_level, reorder_point, reorder_quantity, supplier_id, supplier_lead_time, customer_age, customer_gender, customer_income, customer_loyalty_level, payment_method, promotion_applied, promotion_type, weather_conditions, holiday_indicator, weekday, stockout_indicator, forecasted_demand, actual_demand, revenue, forecast_error]
Index: []

[0 rows x 30 columns]

In [32]:
# Check minimum and maximum demand
query = """
select 
    min(forecasted_demand) as min_forecasted_demand,
    max(forecasted_demand) as max_forecasted_demand,
    min(actual_demand) as min_actual_demand,
    max(actual_demand) as max_actual_demand
from walmart_sales;
"""

result = pd.read_sql(query, engine)
result

,min_forecasted_demand,max_forecasted_demand,min_actual_demand,max_actual_demand
0,100,500,90,510

In [33]:
# Are Boolean columns correctly stored?  
query = """
select promotion_applied, count(*) as total_records
from walmart_sales
group by promotion_applied;
"""
result = pd.read_sql(query, engine)
result

   promotion_applied  total_records
0                  1           2607
1                  0           2393

In [34]:
query = """
select *
from walmart_sales
where promotion_applied not in (0, 1)
   or stockout_indicator not in (0, 1)
   or holiday_indicator not in (0, 1);
"""

result = pd.read_sql(query, engine)
result

Empty DataFrame
Columns: [transaction_id, customer_id, product_id, product_name, category, quantity_sold, unit_price, transaction_date, store_id, store_location, inventory_level, reorder_point, reorder_quantity, supplier_id, supplier_lead_time, customer_age, customer_gender, customer_income, customer_loyalty_level, payment_method, promotion_applied, promotion_type, weather_conditions, holiday_indicator, weekday, stockout_indicator, forecasted_demand, actual_demand, revenue, forecast_error]
Index: []

[0 rows x 30 columns]

In [35]:
# Are store names standardized?
query = """
select store_location,count(*) as total_records
from walmart_sales
group by store_location
order by store_location;
"""

result = pd.read_sql(query,engine)
result

    store_location  total_records
0      Chicago, IL           1013
1       Dallas, TX            998
2  Los Angeles, CA           1038
3        Miami, FL            964
4     New York, NY            987

In [36]:
# Are product names standardized?
query = """ 
select product_name,count(*) as total_records
from walmart_sales
group by product_name
order by product_name;
"""

result = pd.read_sql(query,engine)
result

      product_name  total_records
0           Camera            628
1           Fridge            655
2       Headphones            614
3           Laptop            578
4       Smartphone            641
5           Tablet            647
6               TV            623
7  Washing Machine            614

In [37]:
# Can we extract year, month, and quarter from transaction_date to analyze sales trends over time 
query = """
alter table walmart_sales
add column transaction_year int,
add column transaction_month int,
add column transaction_quarter int;
"""

with engine.begin() as conn:
    conn.execute(text(query))

print("columns added successfully")

columns added successfully

In [38]:
query = """
update walmart_sales
set 
    transaction_year = year(transaction_date),
    transaction_month = month(transaction_date),
    transaction_quarter = quarter(transaction_date)
where transaction_date is not null;
"""

with engine.begin() as conn:
    conn.execute(text(query))

print('Year, Month , and quarter updated successfully')

Year, Month , and quarter updated successfully

In [39]:
query = """
select 
    transaction_date,
    transaction_year,
    transaction_month,
    transaction_quarter
from walmart_sales
limit 10;
"""

result = pd.read_sql(query, engine)
result

,transaction_date,transaction_year,transaction_month,transaction_quarter
0,2024-03-31 21:46:00,2024,3,1
1,2024-07-28 12:45:00,2024,7,3
2,2024-06-10 04:55:00,2024,6,2
3,2024-08-15 01:03:00,2024,8,3
4,2024-09-13 00:45:00,2024,9,3
5,2024-07-06 07:24:00,2024,7,3
6,2024-03-17 22:33:00,2024,3,1
7,2024-07-22 13:57:00,2024,7,3
8,2024-03-30 04:10:00,2024,3,1
9,2024-06-17 16:59:00,2024,6,2

In [40]:
query = """
alter table walmart_sales
add column forecast_error_percentage decimal(10,2);
"""

with engine.begin() as conn:
    conn.execute(text(query))

In [41]:
# Create forecast_error_percentage column
query = """
update walmart_sales
set forecast_error_percentage =
    case
        when actual_demand = 0 then null
        else (abs(forecasted_demand - actual_demand) / actual_demand) * 100
    end;
"""

with engine.begin() as conn:
    conn.execute(text(query))

In [42]:
query = """
select 
    forecasted_demand,
    actual_demand,
    forecast_error_percentage
from walmart_sales
limit 10;
"""

result = pd.read_sql(query, engine)
result

   forecasted_demand  actual_demand  forecast_error_percentage
0                172            179                       3.91
1                109            484                      77.48
2                289            416                      30.53
3                174            446                      60.99
4                287            469                      38.81
5                294            265                      10.94
6                178            257                      30.74
7                165            264                      37.50
8                476            428                      11.21
9                395            400                       1.25

In [43]:
# How much inventory gap exists between available stock and actual demand?
query = """
alter table walmart_sales
add column inventory_gap bigint;
"""
with engine.connect() as conn:
    conn.execute(text(query))
    conn.commit()

In [44]:
query = """
update walmart_sales
set inventory_gap = inventory_level - actual_demand;
"""

with engine.begin() as conn:
    conn.execute(text(query))

In [45]:
query = """
select 
    inventory_level,
    actual_demand,
    inventory_gap
from walmart_sales
limit 10;
"""

result = pd.read_sql(query, engine)
result

   inventory_level  actual_demand  inventory_gap
0              246            179             67
1               43            484           -441
2              411            416             -5
3              452            446              6
4              412            469            -57
5              196            265            -69
6               24            257           -233
7              125            264           -139
8              103            428           -325
9              424            400             24

In [46]:
#which products are understocked and need to be reordered?
query = """
alter table walmart_sales
add column understock_flag tinyint,
add column reorder_required tinyint;
"""

with engine.begin() as conn:
    conn.execute(text(query))

In [47]:
query = """
update walmart_sales
set
    understock_flag = case
        when inventory_level < actual_demand then 1
        else 0
    end,
    
    reorder_required = case
        when inventory_level <= reorder_point then 1
        else 0
    end;
"""

with engine.begin() as conn:
    conn.execute(text(query))

In [48]:
query = """
update walmart_sales
set
    understock_flag = case
        when inventory_level < actual_demand then 1
        else 0
    end,
    
    reorder_required = case
        when inventory_level <= reorder_point then 1
        else 0
    end;
"""

with engine.begin() as conn:
    conn.execute(text(query))

In [49]:
query = """
select
    product_name,
    inventory_level,
    actual_demand,
    reorder_point,
    understock_flag,
    reorder_required
from walmart_sales
limit 10;
"""

result = pd.read_sql(query, engine)
result

,product_name,inventory_level,actual_demand,reorder_point,understock_flag,reorder_required
0,Fridge,246,179,116,0,0
1,TV,43,484,70,1,1
2,Fridge,411,416,94,1,0
3,Smartphone,452,446,87,0,0
4,Laptop,412,469,99,1,0
5,Camera,196,265,80,1,0
6,Laptop,24,257,52,1,1
7,Tablet,125,264,92,1,0
8,Camera,103,428,129,1,1
9,Laptop,424,400,88,0,0

In [50]:
# what are the executive kpis for walmart sales performance?

query = """
select
    round(sum(quantity_sold * unit_price), 2) as total_revenue,

    sum(quantity_sold) as total_quantity_sold,

    count(distinct transaction_id) as total_number_of_transactions,

    round(
        sum(quantity_sold * unit_price) / count(distinct transaction_id),
        2
    ) as average_transaction_value,

    round(avg(unit_price), 2) as average_unit_price,

    sum(actual_demand) as total_actual_demand,

    sum(forecasted_demand) as total_forecasted_demand,

    round(
        sum(case when stockout_indicator = 1 then 1 else 0 end) / count(*) * 100.0,
        2
    ) as stockout_rate_percentage,

    round(
        sum(case when inventory_level < actual_demand then 1 else 0 end) / count(*) * 100.0,
        2
    ) as understock_rate_percentage,

    round(
        sum(case when promotion_applied = 1 then 1 else 0 end) / count(*) * 100.0,
        2
    ) as promotion_usage_rate_percentage

from walmart_sales;
"""

result = pd.read_sql(query, engine)
result

,total_revenue,total_quantity_sold,total_number_of_transactions,average_transaction_value,average_unit_price,total_actual_demand,total_forecasted_demand,stockout_rate_percentage,understock_rate_percentage,promotion_usage_rate_percentage
0,15263601.45,14914.0,5000,3052.72,1023.47,1495442.0,1485670.0,51.86,59.8,52.14

## Sales Performance Analysis

***Business Problem :
Walmart wants to know which products, stores, and categories are driving revenue.***

In [51]:
# Which category generates the highest revenue?  
query = """
select category,sum(revenue) as total_revenue 
from walmart_sales
group by category 
order by total_revenue desc;
"""
result = pd.read_sql(query,engine)
result

      category  total_revenue
0  Electronics     7941631.80
1   Appliances     7321969.65

In [52]:
# Which product generates the highest revenue? 
query = """
select product_name,sum(revenue) as total_revenue
from walmart_sales
group by product_name
order by total_revenue desc limit 1;
"""
result = pd.read_sql(query,engine)
result

  product_name  total_revenue
0           TV     2049493.86

In [53]:
# Which store location generates the highest revenue?  
query = """
select store_location,sum(revenue) as total_revenue
from walmart_sales
group by store_location
order by total_revenue desc limit 1;
"""
result = pd.read_sql(query,engine)
result

    store_location  total_revenue
0  Los Angeles, CA     3276299.63

In [54]:
# Which store has the lowest revenue? 
query = """
select store_location,sum(revenue) as total_revenue
from walmart_sales
group by store_location
order by total_revenue asc limit 1;
"""
result = pd.read_sql(query,engine)
result

  store_location  total_revenue
0     Dallas, TX     2903930.74

In [55]:
# Which weekday generates the highest sales? 
query = """
select weekday,sum(revenue) as total_revenue
from walmart_sales
group by weekday
order by total_revenue desc limit 1;
"""
result = pd.read_sql(query,engine)
result

    weekday  total_revenue
0  Thursday     2436640.72

In [56]:
# Which month has the highest revenue? 
# business question: which month has the highest revenue?

query = """
select 
    monthname(transaction_date) as transaction_month_name,
    month(transaction_date) as transaction_month_number,
    round(sum(revenue), 2) as total_revenue
from walmart_sales
group by transaction_month_name, transaction_month_number
order by total_revenue desc
limit 1;
"""

result = pd.read_sql(query, engine)
result

  transaction_month_name  transaction_month_number  total_revenue
0                 August                         8     2018315.81

In [57]:
# Which category has the highest quantity sold? 
query = """
select category,sum(quantity_sold) as Highest_quantity_sold
from walmart_sales
group by category
order by Highest_quantity_sold desc limit 1;
"""

result = pd.read_sql(query,engine)
result

      category  Highest_quantity_sold
0  Electronics                 7745.0

In [58]:
# Which payment method contributes the most revenue? 
query = """
select payment_method ,sum(revenue) as total_revenue
from walmart_sales
group by payment_method
order by total_revenue desc limit 1;
"""

result = pd.read_sql(query,engine)
result

   payment_method  total_revenue
0  Digital Wallet     3964782.71

In [59]:
# Which customer loyalty level generates the most revenue? 
query = """
select customer_loyalty_level ,sum(revenue) as total_revenue
from walmart_sales
group by customer_loyalty_level
order by total_revenue desc limit 1;
"""

result = pd.read_sql(query,engine)
result

  customer_loyalty_level  total_revenue
0               Platinum     4012963.14

In [60]:
 # which products have high quantity sold but low revenue?
query = """
with product_summary as (
    select 
        product_name,
        sum(quantity_sold) as total_quantity_sold,
        round(sum(revenue), 2) as total_revenue,
        round(avg(unit_price), 2) as average_unit_price
    from walmart_sales
    group by product_name
),
product_avg as (
    select
        avg(total_quantity_sold) as avg_quantity_sold,
        avg(total_revenue) as avg_revenue
    from product_summary
)
select 
    ps.product_name,
    ps.total_quantity_sold,
    ps.total_revenue,
    ps.average_unit_price
from product_summary ps
cross join product_avg pa
where ps.total_quantity_sold > pa.avg_quantity_sold
and ps.total_revenue < pa.avg_revenue
order by ps.total_quantity_sold desc;
"""

result = pd.read_sql(query, engine)
result

  product_name  total_quantity_sold  total_revenue  average_unit_price
0       Camera               1873.0     1895104.13             1015.64

## Store Performance Analysis

***Business Problem :
Management wants to compare store performance and identify weak locations**

In [61]:
# Which store has the highest revenue? 
query = """ 
select store_id,store_location, 
round(sum(revenue),2) as total_Revenue 
from walmart_sales
group by store_id, store_location 
order by total_revenue desc 
limit 1;
"""
result = pd.read_sql(query, engine)
result

   store_id store_location  total_Revenue
0        17     Dallas, TX      213954.02

In [62]:
# Which store has the lowest revenue? 
query = """ 
select store_id,store_location, 
round(sum(revenue),2) as total_Revenue 
from walmart_sales
group by store_id, store_location 
order by total_revenue asc 
limit 1;
"""
result = pd.read_sql(query, engine)
result

   store_id store_location  total_Revenue
0         6   New York, NY       80279.62

In [63]:
# Which store has the highest number of transactions? 
query = """ 
select store_id,store_location, 
count(distinct transaction_id) as highest_number_of_transaction 
from walmart_sales
group by store_id, store_location 
order by  highest_number_of_transaction desc
limit 1;
"""
result = pd.read_sql(query, engine)
result

   store_id store_location  highest_number_of_transaction
0        14   New York, NY                             73

In [64]:
# Which store has the highest average transaction value?
query = """
select store_id,
    store_location,
    round(sum(quantity_sold * unit_price), 2) as total_revenue,
    count(distinct transaction_id) as total_transactions,
    round(sum(quantity_sold * unit_price) / count(distinct transaction_id), 2) as average_transaction_value
from walmart_sales
group by store_id, store_location
order by average_transaction_value desc
limit 1;
"""

result = pd.read_sql(query, engine)
result

,store_id,store_location,total_revenue,total_transactions,average_transaction_value
0,11,"Chicago, IL",205997.8,51,4039.17

In [65]:
# Which store has the highest stockout rate?
query = """
select 
    store_id,
    store_location,
    round(
        sum(case when stockout_indicator = 1 then 1 else 0 end) / count(*) * 100,
        2
    ) as stockout_rate_percentage
from walmart_sales
group by store_id, store_location
order by stockout_rate_percentage desc
limit 1;
"""

result = pd.read_sql(query, engine)
result

   store_id store_location  stockout_rate_percentage
0        20   New York, NY                     66.07

In [66]:
# Which store has the highest forecast error?
query = """
select store_id,store_location,
round(avg(case when actual_demand = 0 then null
else abs (forecasted_demand - actual_demand) / actual_demand * 100 end ),
2
) as average_forecast_error_percentage
from walmart_sales
group by store_id,store_location
order by average_forecast_error_percentage desc
limit 1;
"""

result = pd.read_sql(query, engine)
result

   store_id store_location  average_forecast_error_percentage
0        12   New York, NY                              88.14

In [67]:
# Which store has the highest promotion usage
query = """
select store_id,store_location,
round(
sum(case when promotion_applied = 1 then 1 else 0 end) / count(*) * 100,
2
) as promotion_usage_percentage
from walmart_sales
group by store_id, store_location
order by promotion_usage_percentage desc
limit 1;
"""

result = pd.read_sql(query, engine)
result

   store_id   store_location  promotion_usage_percentage
0        20  Los Angeles, CA                       68.75

In [68]:
# Which store has high revenue but poor inventory health?
query = """
with store_summary as (
    select 
        store_id,
        store_location,
        round(sum(quantity_sold * unit_price), 2) as total_revenue,

        round(
            sum(case when stockout_indicator = 1 then 1 else 0 end) / count(*) * 100,
            2
        ) as stockout_rate_percentage,

        round(
            sum(case when inventory_level < actual_demand then 1 else 0 end) / count(*) * 100,
            2
        ) as understock_rate_percentage,

        round(
            avg(
                case
                    when actual_demand = 0 then null
                    else abs(forecasted_demand - actual_demand) / actual_demand * 100
                end
            ),
            2
        ) as average_forecast_error_percentage
    from walmart_sales
    group by store_id, store_location
),
average_summary as (
    select avg(total_revenue) as average_revenue
    from store_summary
)
select 
    s.*,
    round(
        stockout_rate_percentage + understock_rate_percentage + average_forecast_error_percentage,
        2
    ) as inventory_risk_score
from store_summary s
cross join average_summary a
where s.total_revenue > a.average_revenue
order by inventory_risk_score desc
limit 1;
"""

result = pd.read_sql(query, engine)
result

,store_id,store_location,total_revenue,stockout_rate_percentage,understock_rate_percentage,average_forecast_error_percentage,inventory_risk_score
0,13,"Los Angeles, CA",171842.06,63.46,61.54,70.57,195.57

In [69]:
# Which store has low revenue and high stockout risk?
query = """
with store_summary as (
    select 
        store_id,
        store_location,
        round(sum(quantity_sold * unit_price), 2) as total_revenue,

        round(
            sum(case when stockout_indicator = 1 then 1 else 0 end) / count(*) * 100,
            2
        ) as stockout_rate_percentage
    from walmart_sales
    group by store_id, store_location
),
average_summary as (
    select 
        avg(total_revenue) as average_revenue,
        avg(stockout_rate_percentage) as average_stockout_rate
    from store_summary
)
select 
    s.store_id,
    s.store_location,
    s.total_revenue,
    s.stockout_rate_percentage
from store_summary s
cross join average_summary a
where s.total_revenue < a.average_revenue
and s.stockout_rate_percentage > a.average_stockout_rate
order by s.stockout_rate_percentage desc, s.total_revenue asc
limit 1;
"""

result = pd.read_sql(query, engine)
result

   store_id store_location  total_revenue  stockout_rate_percentage
0         5   New York, NY      138666.36                     65.96

In [70]:
# Which store needs immediate operational attention?
query = """
with store_summary as (
    select 
        store_id,
        store_location,
        round(sum(quantity_sold * unit_price), 2) as total_revenue,

        round(
            sum(case when stockout_indicator = 1 then 1 else 0 end) / count(*) * 100,
            2
        ) as stockout_rate_percentage,

        round(
            sum(case when inventory_level < actual_demand then 1 else 0 end) / count(*) * 100,
            2
        ) as understock_rate_percentage,

        round(
            avg(
                case
                    when actual_demand = 0 then null
                    else abs(forecasted_demand - actual_demand) / actual_demand * 100
                end
            ),
            2
        ) as average_forecast_error_percentage
    from walmart_sales
    group by store_id, store_location
)
select 
    store_id,
    store_location,
    total_revenue,
    stockout_rate_percentage,
    understock_rate_percentage,
    average_forecast_error_percentage,
    round(
        stockout_rate_percentage + understock_rate_percentage + average_forecast_error_percentage,
        2
    ) as operational_risk_score
from store_summary
order by operational_risk_score desc
limit 1;
"""

result = pd.read_sql(query, engine)
result

,store_id,store_location,total_revenue,stockout_rate_percentage,understock_rate_percentage,average_forecast_error_percentage,operational_risk_score
0,1,"Dallas, TX",129112.46,56.52,67.39,76.84,200.75

In [71]:
#which stores need operational attention based on revenue, stockout, forecast error, and promotion usage?

query = """
with store_scorecard as (
    select
        store_id,
        store_location,

        round(sum(quantity_sold * unit_price), 2) as store_revenue,

        count(distinct transaction_id) as transactions,

        round(
            sum(quantity_sold * unit_price) / nullif(count(distinct transaction_id), 0),
            2
        ) as avg_transaction_value,

        round(
            sum(case when stockout_indicator = 1 then 1 else 0 end) / count(*) * 100,
            2
        ) as stockout_rate,

        round(
            avg(
                case
                    when actual_demand = 0 then null
                    else abs(forecasted_demand - actual_demand) / actual_demand * 100
                end
            ),
            2
        ) as forecast_error_percentage,

        round(
            sum(case when promotion_applied = 1 then 1 else 0 end) / count(*) * 100,
            2
        ) as promotion_usage_percentage

    from walmart_sales
    group by store_id, store_location
),

store_averages as (
    select
        avg(store_revenue) as avg_store_revenue,
        avg(stockout_rate) as avg_stockout_rate,
        avg(forecast_error_percentage) as avg_forecast_error
    from store_scorecard
)

select
    s.store_id,
    s.store_location,
    s.store_revenue,
    s.transactions,
    s.avg_transaction_value,
    s.stockout_rate,
    s.forecast_error_percentage,
    s.promotion_usage_percentage,

    case
        when s.store_revenue < a.avg_store_revenue
             and s.stockout_rate > a.avg_stockout_rate
             and s.forecast_error_percentage > a.avg_forecast_error
        then concat(
            'store ', s.store_id,
            ' needs attention because revenue is low, stockout rate is high, and forecast error is above average.'
        )

        when s.store_revenue > a.avg_store_revenue
             and s.stockout_rate > a.avg_stockout_rate
        then concat(
            'store ', s.store_id,
            ' has strong revenue but poor inventory health because stockout rate is above average.'
        )

        when s.forecast_error_percentage > a.avg_forecast_error
        then concat(
            'store ', s.store_id,
            ' needs demand forecasting improvement because forecast error is above average.'
        )

        when s.stockout_rate > a.avg_stockout_rate
        then concat(
            'store ', s.store_id,
            ' needs inventory monitoring because stockout rate is above average.'
        )

        else concat(
            'store ', s.store_id,
            ' is performing normally based on current revenue and inventory risk metrics.'
        )
    end as business_recommendation

from store_scorecard s
cross join store_averages a
order by 
    s.stockout_rate desc,
    s.forecast_error_percentage desc,
    s.store_revenue asc;
"""

store_scorecard = pd.read_sql(query, engine)
store_scorecard

,store_id,store_location,store_revenue,transactions,avg_transaction_value,stockout_rate,forecast_error_percentage,promotion_usage_percentage,business_recommendation
0,20,"New York, NY",195221.76,56,3486.10,66.07,74.39,53.57,store 20 has strong revenue but poor inventory...
1,5,"New York, NY",138666.36,47,2950.35,65.96,55.70,51.06,store 5 needs inventory monitoring because sto...
2,14,"New York, NY",203837.41,73,2792.29,65.75,62.11,53.42,store 14 has strong revenue but poor inventory...
3,16,"Los Angeles, CA",201977.38,62,3257.70,64.52,71.04,43.55,store 16 has strong revenue but poor inventory...
4,13,"Dallas, TX",120594.18,58,2079.21,63.79,75.32,39.66,store 13 needs attention because revenue is lo...
...,...,...,...,...,...,...,...,...,...
95,20,"Chicago, IL",119403.93,48,2487.58,39.58,64.74,54.17,store 20 needs demand forecasting improvement ...
96,6,"Dallas, TX",146921.19,48,3060.86,37.50,54.80,47.92,store 6 is performing normally based on curren...
97,5,"Miami, FL",170695.90,59,2893.15,37.29,59.08,42.37,store 5 is performing normally based on curren...
98,14,"Chicago, IL",142354.70,48,2965.72,35.42,60.27,54.17,store 14 needs demand forecasting improvement ...
99,10,"Los Angeles, CA",163846.03,49,3343.80,34.69,57.77,44.90,store 10 is performing normally based on curre...

## Inventory Risk Analysis
***Business Problem :
Stockouts directly cause lost sales and poor customer experience. Walmart needs to identify inventory risk areas.***

In [72]:
# What is the overall stockout rate? 
query = """
select 
    round(avg(stockout_indicator) * 100, 2) as overall_stockout_rate_percentage
from walmart_sales;
"""

result = pd.read_sql(query, engine)
result

   overall_stockout_rate_percentage
0                             51.86

In [73]:
# Which store has the highest stockout rate?  
query = """
select 
    store_id,
    store_location,
    count(*) as total_records,
    sum(stockout_indicator) as total_stockouts,
    round(avg(stockout_indicator) * 100, 2) as stockout_rate_percentage
from walmart_sales
group by store_id, store_location
order by stockout_rate_percentage desc
limit 1;
"""

result = pd.read_sql(query, engine)
result

,store_id,store_location,total_records,total_stockouts,stockout_rate_percentage
0,20,"New York, NY",56,37.0,66.07

In [74]:
# Which products have inventory below reorder point?
query = """
select 
    product_id,
    product_name,
    category,
    inventory_level,
    reorder_point
from walmart_sales
where inventory_level <= reorder_point
order by inventory_level asc;
"""

result = pd.read_sql(query, engine)
result

     product_id     product_name     category  inventory_level  reorder_point
0           150           Laptop  Electronics                0            117
1           566           Tablet   Appliances                0             56
2           765           Camera  Electronics                0            122
3           119       Smartphone   Appliances                0             76
4           878           Camera  Electronics                0             53
..          ...              ...          ...              ...            ...
940         183           Laptop  Electronics              140            150
941         786           Tablet  Electronics              141            142
942         431  Washing Machine   Appliances              142            149
943         569               TV  Electronics              143            150
944         129           Fridge  Electronics              144            148

[945 rows x 5 columns]

In [75]:
# Which products have actual demand greater than inventory?
query = """
select 
    product_id,
    product_name,
    category,
    inventory_level,
    actual_demand,
    actual_demand - inventory_level as demand_gap
from walmart_sales
where actual_demand > inventory_level
order by demand_gap desc;
"""

result = pd.read_sql(query, engine)
result

,product_id,product_name,category,inventory_level,actual_demand,demand_gap
0,342,Camera,Electronics,1,504,503
1,469,Laptop,Electronics,3,503,500
2,973,Fridge,Electronics,16,509,493
3,943,Headphones,Appliances,15,507,492
4,607,Fridge,Electronics,13,504,491
...,...,...,...,...,...,...
2985,616,Laptop,Appliances,345,346,1
2986,218,Camera,Electronics,493,494,1
2987,908,Camera,Electronics,243,244,1
2988,347,Laptop,Electronics,272,273,1
2989,738,Tablet,Electronics,172,173,1

In [76]:
# Which products are understocked most frequently?
query = """
select 
    product_id,
    product_name,
    count(*) as understock_frequency
from walmart_sales
where inventory_level < actual_demand
group by product_id, product_name
order by understock_frequency desc
limit 10;
"""

result = pd.read_sql(query, engine)
result

   product_id     product_name  understock_frequency
0         155           Fridge                     5
1         653           Tablet                     5
2         526  Washing Machine                     4
3         491           Laptop                     4
4         215           Fridge                     4
5         537       Headphones                     4
6         882       Smartphone                     4
7         343       Smartphone                     4
8         645  Washing Machine                     3
9         187               TV                     3

In [77]:
# Which products have high demand but low inventory?
query = """
select 
    product_id,
    product_name,
    category,
    round(avg(actual_demand), 2) as average_actual_demand,
    round(avg(inventory_level), 2) as average_inventory_level,
    round(avg(actual_demand) - avg(inventory_level), 2) as demand_inventory_gap
from walmart_sales
group by product_id, product_name, category
having average_actual_demand > average_inventory_level
order by demand_inventory_gap desc
limit 10;
"""

result = pd.read_sql(query, engine)
result

,product_id,product_name,category,average_actual_demand,average_inventory_level,demand_inventory_gap
0,342,Camera,Electronics,504.0,1.0,503.0
1,469,Laptop,Electronics,503.0,3.0,500.0
2,943,Headphones,Appliances,507.0,15.0,492.0
3,607,Fridge,Electronics,504.0,13.0,491.0
4,979,TV,Appliances,506.0,18.0,488.0
5,743,Headphones,Appliances,508.0,21.0,487.0
6,713,TV,Appliances,503.0,21.0,482.0
7,673,Headphones,Electronics,509.0,28.0,481.0
8,119,Laptop,Appliances,495.0,17.0,478.0
9,288,Laptop,Appliances,502.0,26.0,476.0

In [78]:
# Which suppliers are linked to products with stockout problems
query = """
select 
    supplier_id,
    count(distinct product_id) as affected_products,
    sum(stockout_indicator) as total_stockout_cases,
    round(avg(stockout_indicator) * 100, 2) as stockout_rate_percentage
from walmart_sales
group by supplier_id
order by total_stockout_cases desc
limit 10;
"""

result = pd.read_sql(query, engine)
result

,supplier_id,affected_products,total_stockout_cases,stockout_rate_percentage
0,470,24,16.0,66.67
1,442,18,14.0,77.78
2,289,20,14.0,70.00
3,405,18,14.0,73.68
4,333,13,13.0,100.00
5,283,16,13.0,81.25
6,170,15,13.0,86.67
7,131,20,13.0,65.00
8,231,17,13.0,76.47
9,366,19,13.0,68.42

In [79]:
# Which products should be reordered immediately?
query = """
select 
    product_id,
    product_name,
    category,
    inventory_level,
    reorder_point,
    actual_demand,
    actual_demand - inventory_level as demand_gap
from walmart_sales
where inventory_level <= reorder_point
   or actual_demand > inventory_level
order by demand_gap desc;
"""

result = pd.read_sql(query, engine)
result

,product_id,product_name,category,inventory_level,reorder_point,actual_demand,demand_gap
0,342,Camera,Electronics,1,77,504,503
1,469,Laptop,Electronics,3,128,503,500
2,973,Fridge,Electronics,16,139,509,493
3,943,Headphones,Appliances,15,87,507,492
4,607,Fridge,Electronics,13,60,504,491
...,...,...,...,...,...,...,...
2992,146,Smartphone,Appliances,111,134,101,-10
2993,804,Washing Machine,Electronics,123,140,110,-13
2994,267,Headphones,Electronics,110,146,96,-14
2995,802,Smartphone,Appliances,116,132,95,-21
2996,432,Fridge,Appliances,118,148,94,-24

## Demand Forecasting Accuracy Analysis

***Business Problem :
Poor forecasting creates two problems: stockouts and overstocking.***

In [80]:
# What is the average forecast error?
query = """
select 
    round(avg(abs(forecasted_demand - actual_demand)), 2) as average_forecast_error
from walmart_sales;
"""

result = pd.read_sql(query, engine)
result

   average_forecast_error
0                  137.52

In [81]:
# What is the average forecast error percentage?
query = """
select 
    round(
        avg(
            case 
                when actual_demand = 0 then null
                else abs(forecasted_demand - actual_demand) / actual_demand * 100.0
            end
        ), 2
    ) as average_forecast_error_percentage
from walmart_sales;
"""

result = pd.read_sql(query, engine)
result

   average_forecast_error_percentage
0                              59.93

In [82]:
# Which products have the highest forecast error?
query = """
select 
    product_id,
    product_name,
    round(avg(abs(forecasted_demand - actual_demand)), 2) as average_forecast_error
from walmart_sales
group by product_id, product_name
order by average_forecast_error desc
limit 10;
"""

result = pd.read_sql(query, engine)
result

   product_id product_name  average_forecast_error
0         142       Laptop                   406.0
1         109       Fridge                   405.0
2         444       Fridge                   400.0
3         842       Camera                   398.0
4         573   Headphones                   396.0
5         394       Tablet                   396.0
6         760   Headphones                   392.0
7         612       Laptop                   392.0
8         800       Fridge                   391.0
9         248           TV                   391.0

In [83]:
# Which stores have the highest forecast error?
query = """
select 
    store_id,
    store_location,
    round(avg(abs(forecasted_demand - actual_demand)), 2) as average_forecast_error
from walmart_sales
group by store_id, store_location
order by average_forecast_error desc
limit 10;
"""

result = pd.read_sql(query, engine)
result

   store_id   store_location  average_forecast_error
0         1       Dallas, TX                  176.54
1        12        Miami, FL                  160.46
2        16     New York, NY                  159.50
3         5     New York, NY                  158.47
4        20     New York, NY                  158.20
5        18        Miami, FL                  157.81
6        19     New York, NY                  156.37
7        17        Miami, FL                  156.34
8        10       Dallas, TX                  155.71
9         3  Los Angeles, CA                  155.49

In [84]:
# Which categories are poorly forecasted?
query = """
select 
    category,
    round(avg(abs(forecasted_demand - actual_demand)), 2) as average_forecast_error,
    round(
        avg(
            case 
                when actual_demand = 0 then null
                else abs(forecasted_demand - actual_demand) / actual_demand * 100.0
            end
        ), 2
    ) as average_forecast_error_percentage
from walmart_sales
group by category
order by average_forecast_error_percentage desc
limit 10;
"""

result = pd.read_sql(query, engine)
result

      category  average_forecast_error  average_forecast_error_percentage
0   Appliances                  139.32                              61.83
1  Electronics                  135.83                              58.15

In [85]:
# is Walmart mostly under-forecasting or over-forecasting demand?
query = """
select 
    case
        when forecasted_demand < actual_demand then 'under_forecasted'
        when forecasted_demand > actual_demand then 'over_forecasted'
        else 'accurate_forecast'
    end as forecast_status,
    count(*) as total_records,
    round(count(*) / (select count(*) from walmart_sales) * 100.0, 2) as percentage
from walmart_sales
group by forecast_status
order by total_records desc;
"""

result = pd.read_sql(query, engine)
result

     forecast_status  total_records  percentage
0   under_forecasted           2555       51.10
1    over_forecasted           2436       48.72
2  accurate_forecast              9        0.18

In [86]:
# Which products have actual demand much higher than forecasted demand?
query = """
select 
    product_id,
    product_name,
    category,
    round(avg(actual_demand), 2) as average_actual_demand,
    round(avg(forecasted_demand), 2) as average_forecasted_demand,
    round(avg(actual_demand - forecasted_demand), 2) as under_forecast_gap
from walmart_sales
where actual_demand > forecasted_demand
group by product_id, product_name, category
order by under_forecast_gap desc
limit 10;
"""

result = pd.read_sql(query, engine)
result

,product_id,product_name,category,average_actual_demand,average_forecasted_demand,under_forecast_gap
0,444,Fridge,Electronics,504.0,104.0,400.0
1,722,Camera,Appliances,509.0,110.0,399.0
2,573,Headphones,Electronics,506.0,110.0,396.0
3,760,Headphones,Electronics,508.0,116.0,392.0
4,183,Laptop,Electronics,503.0,113.0,390.0
5,511,Headphones,Electronics,500.0,112.0,388.0
6,954,Tablet,Appliances,506.0,124.0,382.0
7,529,TV,Appliances,497.0,115.0,382.0
8,900,Headphones,Electronics,495.0,116.0,379.0
9,751,TV,Electronics,497.0,118.0,379.0

In [87]:
# Which products have forecasted demand much higher than actual demand?
query = """
select 
    product_id,
    product_name,
    category,
    round(avg(forecasted_demand), 2) as average_forecasted_demand,
    round(avg(actual_demand), 2) as average_actual_demand,
    round(avg(forecasted_demand - actual_demand), 2) as over_forecast_gap
from walmart_sales
where forecasted_demand > actual_demand
group by product_id, product_name, category
order by over_forecast_gap desc
limit 10;
"""

result = pd.read_sql(query, engine)
result

,product_id,product_name,category,average_forecasted_demand,average_actual_demand,over_forecast_gap
0,142,Laptop,Electronics,497.0,91.0,406.0
1,109,Fridge,Electronics,500.0,95.0,405.0
2,842,Camera,Electronics,495.0,97.0,398.0
3,394,Tablet,Appliances,491.0,95.0,396.0
4,612,Laptop,Appliances,492.0,100.0,392.0
5,800,Fridge,Appliances,489.0,98.0,391.0
6,248,TV,Electronics,497.0,106.0,391.0
7,511,Washing Machine,Appliances,494.0,107.0,387.0
8,857,Laptop,Appliances,492.0,108.0,384.0
9,666,Laptop,Appliances,496.0,112.0,384.0

In [88]:
# Is forecast error higher during holidays?
query = """
select 
    holiday_indicator,
    case 
        when holiday_indicator = 1 then 'holiday'
        else 'non_holiday'
    end as day_type,
    round(avg(abs(forecasted_demand - actual_demand)), 2) as average_forecast_error,
    round(
        avg(
            case 
                when actual_demand = 0 then null
                else abs(forecasted_demand - actual_demand) / actual_demand * 100.0
            end
        ), 2
    ) as average_forecast_error_percentage
from walmart_sales
group by holiday_indicator, day_type
order by average_forecast_error_percentage desc;
"""

result = pd.read_sql(query, engine)
result

,holiday_indicator,day_type,average_forecast_error,average_forecast_error_percentage
0,1,holiday,139.55,60.74
1,0,non_holiday,135.48,59.11

In [89]:
# is forecast error higher during promotions
query = """
select
    case
        when promotion_applied = 1 then 'promotion'
        else 'no promotion'
    end as promotion_status,

    count(*) as total_records,

    round(
        avg(
            abs(forecasted_demand - actual_demand) / nullif(actual_demand, 0) * 100
        ),
        2
    ) as avg_forecast_error_percentage

from walmart_sales
group by promotion_applied
order by avg_forecast_error_percentage desc;
"""

result = pd.read_sql(query, engine)
result

  promotion_status  total_records  avg_forecast_error_percentage
0     no promotion           2393                           60.4
1        promotion           2607                           59.5

In [90]:
query = """
describe walmart_sales;
"""

result = pd.read_sql(query, engine)
result

                        Field           Type Null Key Default Extra
0              transaction_id         bigint  YES        None
1                 customer_id         bigint  YES        None
2                  product_id         bigint  YES        None
3                product_name           text  YES        None
4                    category           text  YES        None
5               quantity_sold         bigint  YES        None
6                  unit_price         double  YES        None
7            transaction_date       datetime  YES        None
8                    store_id         bigint  YES        None
9              store_location           text  YES        None
10            inventory_level         bigint  YES        None
11              reorder_point         bigint  YES        None
12           reorder_quantity         bigint  YES        None
13                supplier_id         bigint  YES        None
14         supplier_lead_time         bigint  YES        None
15               customer_age         bigint  YES        None
16            customer_gender           text  YES        None
17            customer_income         double  YES        None
18     customer_loyalty_level           text  YES        None
19             payment_method           text  YES        None
20          promotion_applied     tinyint(1)  YES        None
21             promotion_type           text  YES        None
22         weather_conditions           text  YES        None
23          holiday_indicator     tinyint(1)  YES        None
24                    weekday           text  YES        None
25         stockout_indicator     tinyint(1)  YES        None
26          forecasted_demand         bigint  YES        None
27              actual_demand         bigint  YES        None
28                    revenue         double  YES        None
29             forecast_error         bigint  YES        None
30           transaction_year            int  YES        None
31          transaction_month            int  YES        None
32        transaction_quarter            int  YES        None
33  forecast_error_percentage  decimal(10,2)  YES        None
34              inventory_gap         bigint  YES        None
35            understock_flag        tinyint  YES        None
36           reorder_required        tinyint  YES        None

In [91]:
query = """
describe walmart_sales_cleaned;
"""

result = pd.read_sql(query, engine)
result

                        Field      Type Null Key Default Extra
0              transaction_id    bigint  YES        None
1                 customer_id    bigint  YES        None
2                  product_id    bigint  YES        None
3                product_name      text  YES        None
4                    category      text  YES        None
5               quantity_sold    bigint  YES        None
6                  unit_price    double  YES        None
7            transaction_date  datetime  YES        None
8                    store_id    bigint  YES        None
9              store_location      text  YES        None
10            inventory_level    bigint  YES        None
11              reorder_point    bigint  YES        None
12           reorder_quantity    bigint  YES        None
13                supplier_id    bigint  YES        None
14         supplier_lead_time    bigint  YES        None
15               customer_age    bigint  YES        None
16            customer_gender      text  YES        None
17            customer_income    double  YES        None
18     customer_loyalty_level      text  YES        None
19             payment_method      text  YES        None
20          promotion_applied    bigint  YES        None
21             promotion_type      text  YES        None
22         weather_conditions      text  YES        None
23          holiday_indicator    bigint  YES        None
24                    weekday      text  YES        None
25         stockout_indicator    bigint  YES        None
26          forecasted_demand    bigint  YES        None
27              actual_demand    bigint  YES        None
28                    revenue    double  YES        None
29             forecast_error    bigint  YES        None
30           transaction_year    bigint  YES        None
31          transaction_month    bigint  YES        None
32        transaction_quarter    bigint  YES        None
33  forecast_error_percentage    double  YES        None
34              inventory_gap    bigint  YES        None
35            understock_flag    bigint  YES        None
36           reorder_required    bigint  YES        None
37                  age_group      text  YES        None
38               income_group      text  YES        None